language: ruby
rvm:
  - 2.0.0
  - 2.1.2
  - 2.2.5
bundler_args: --without test
branches:
  only:
    - master
script:
  - bundle exec rspec spec
  - bundle exec rubocop
addons:
  code_climate:
    repo_token: d2565426bec84943089cd897d8847bbe11d18912481dac2d16d0b60ff14b0453
